customhost = "cloudproject.ccyuwnl3zoe8.us-east-1.rds.amazonaws.com"
customuser = "cloudgroup38"
custompass = "cloudgroup38"
customdb = "employee"
custombucket = "cloudprojectadd"
customregion = "us-east-1"
